# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
# Voxel Thing doesn't have tests (at least for now)
#      - name: Test
#        run: dotnet test --no-build --verbosity normal
      - name: Publish Client
        run: dotnet publish VoxelThing.Client/VoxelThing.Client.csproj -c Release -o publish-client --nologo
      - name: Publish Server
        run: dotnet publish VoxelThing.Server/VoxelThing.Server.csproj -c Release -o publish-server --nologo
      - name: Upload Client
        uses: actions/upload-artifact@v4
        with:
          name: client-net8
          path: publish-client
      - name: Upload Server
        uses: actions/upload-artifact@v4
        with:
          name: server-net8
          path: publish-server
